# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by 
# adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose 
# values do not exceed four million, find the sum of the 
# even-valued terms.

def even_fibbo_sum(limit):
	first = 1
	second = 2

	next = first + second
	fibbo_sum = second

	while next <= limit:
		
		if next%2 == 0:
			fibbo_sum += next
		
		first = second
		second = next
		next = first + second

	return fibbo_sum

print(even_fibbo_sum(4000000))
